#!/usr/bin/env bash
# [What] dnsmasq を DNS フォワーダとして起動し、GitHub 関連ドメインの DNS 応答 IP を
#        リアルタイムで ipset へ自動追加する設定を行う
# [Who]  setup-firewall.sh が root 権限で呼び出す
# [When] ipset 初期構築・iptables ロックダウンより前に実行される
# [Where] コンテナ内の /etc/dnsmasq.d/ および /etc/resolv.conf を操作する
# [Why]  iptables は IP アドレスでしか判断できないが、GitHub の IP は動的に変わる。
#        dnsmasq の --ipset 機能を使うことで、DNS 解決と同時に ipset を更新でき
#        IP 変更後も遅延ゼロで新 IP を許可できる
# [How]  dnsmasq の ipset=/<domain>/<setname> ディレクティブを設定ファイルに書き込み、
#        dnsmasq デーモンを起動してコンテナの DNS を 127.0.0.1 に向け直す

# [Why] コマンド失敗・未定義変数・パイプ失敗で即終了させ、問題を早期に検出する
set -euo pipefail

# [What] dnsmasq が DNS 解決時に IP を追加する ipset の名前
# [Why]  setup-firewall.sh と同じ名前にしないと iptables のルールと一致しなくなる
IPSET_NAME="github-allow"

# [What] dnsmasq に読み込ませる設定ファイルのパス
# [Why]  /etc/dnsmasq.d/ はデフォルトで dnsmasq がインクルードするディレクトリ。
#        ここに置くことでベース設定を変えずに追加設定を注入できる
DNSMASQ_CONF="/etc/dnsmasq.d/github-ipset.conf"

# [What] このスクリプトのログ出力先
# [Why]  setup-firewall.sh と同じファイルに追記することでログを一元管理する
LOG_FILE="/tmp/github-firewall.log"

# [What] タイムスタンプ付きログを標準出力とファイルの両方に書く関数
log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" | tee -a "$LOG_FILE"; }

# [What] コンテナが現在使っている DNS サーバのアドレスを /etc/resolv.conf から取得する
# [Why]  dnsmasq は自分では名前解決せず上流 DNS にフォワードするため、
#        現在の DNS サーバを自動検出することで環境依存をなくす
# [How]  -m1 で最初の nameserver 行だけ取得し、awk で IP 部分を抽出する
UPSTREAM_DNS=$(grep -m1 '^nameserver' /etc/resolv.conf | awk '{print $2}')
# [What] 取得した DNS が空、または既に 127.0.0.1 (ループ) の場合は Google DNS を使う
# [Why]  コンテナ環境によっては resolv.conf が空や 127.0.0.1 の場合があり、
#        そのまま使うと dnsmasq が自分自身に問い合わせる無限ループになる
if [[ -z "$UPSTREAM_DNS" || "$UPSTREAM_DNS" == "127.0.0.1" ]]; then
  UPSTREAM_DNS="8.8.8.8"
fi
log "Upstream DNS: ${UPSTREAM_DNS}"

# [What] ipset "github-allow" を作成する。既に存在する場合はスキップ (-exist)
# [Why]  このスクリプトは再実行されることがある (コンテナ restart など) ため、
#        -exist がないと「既に存在する」エラーで set -e により即終了してしまう
# [How]  hash:net はネットワーク CIDR を効率的に格納するデータ構造。
#        maxelem 65536 は GitHub の大量 IP (actions は数千レンジ) を収容するために必要
ipset create "$IPSET_NAME" hash:net maxelem 65536 -exist

# [What] dnsmasq に読み込ませる設定ファイルをヒアドキュメントで生成する
# [When] 設定ファイルが毎回再生成されることで、ipset 名や上流 DNS の変更が即反映される
# [How]  cat > でファイルを上書き作成する。EOF は引用符なしのためシェル変数が展開される
cat > "$DNSMASQ_CONF" <<EOF
# Auto-generated by setup-dnsmasq.sh — do not edit

# [What] DNS フォワード先の上流サーバ
# [Why]  no-resolv と組み合わせて、/etc/resolv.conf を参照せず確実にこのサーバに転送する
server=${UPSTREAM_DNS}

# [What] /etc/resolv.conf を参照しない設定
# [Why]  このスクリプトが /etc/resolv.conf を 127.0.0.1 に書き換えるため、
#        dnsmasq 自身が resolv.conf を読むと 127.0.0.1 に自己参照して無限ループになる
no-resolv

# [What] dnsmasq が待ち受けるアドレス。ループバックのみに絞る
# [Why]  コンテナ外部 (ホスト OS や他のコンテナ) に DNS サービスを公開する必要がないため
listen-address=127.0.0.1
# [What] listen-address のみでリッスンし、全インターフェースにバインドしない
# [Why]  listen-address と bind-interfaces の組み合わせが推奨設定。これがないと
#        他インターフェースが bind されてしまう場合がある
bind-interfaces

# [What] DNS 応答のキャッシュ保持件数
# [Why]  同一ドメインへの繰り返し解決で上流 DNS への問い合わせを減らしレイテンシを下げる
#        ただし ipset への追加はキャッシュヒット時でも発生する (dnsmasq の仕様)
cache-size=1000

# [What] 以下のドメインを解決したとき、応答に含まれる IP を ipset へ自動追加する
# [Why]  これが dnsmasq --ipset の核心機能。IP 変更後の最初の DNS 解決で即座に ipset が更新され、
#        次の TCP 接続が ACCEPT される。ポーリング更新と違い遅延が生じない
# [How]  ipset=/<domain>/<set-name> の形式で設定する。
#        /<domain>/ はそのドメインの全サブドメインにも自動でマッチする
#        例: /github.com/ → api.github.com, codeload.github.com なども対象
ipset=/github.com/${IPSET_NAME}
ipset=/githubusercontent.com/${IPSET_NAME}
ipset=/githubcopilot.com/${IPSET_NAME}
ipset=/githubassets.com/${IPSET_NAME}
ipset=/github.dev/${IPSET_NAME}
ipset=/ghcr.io/${IPSET_NAME}
ipset=/github.io/${IPSET_NAME}
# [Why] GitHub Copilot の A/B テスト基盤 (default.exp-tas.com) が exp-tas.com に属するため追加
ipset=/exp-tas.com/${IPSET_NAME}
ipset=/githubapp.com/${IPSET_NAME}
ipset=/pkg.github.com/${IPSET_NAME}
EOF

log "dnsmasq config written to ${DNSMASQ_CONF}"

# [What] 既に dnsmasq が起動していれば停止する
# [When] コンテナ restart 時に前回の dnsmasq が残っている場合
# [Why]  旧設定で動いている dnsmasq が新設定を読まないまま動き続けると
#        ipset への追加が正しく行われなくなる
# [How]  pidof で PID が取れた場合のみ killall を実行し、停止失敗は無視する
if pidof dnsmasq &>/dev/null; then
  killall dnsmasq 2>/dev/null || true
  # [Why] dnsmasq はシグナル受信後に完全停止するまでわずかに時間がかかるため、
  #       すぐ再起動するとポート占有エラーになることがある
  sleep 0.5
  log "Stopped existing dnsmasq"
fi

# [What] 生成した設定ファイルで dnsmasq デーモンを起動する
# [Why]  デーモンとして起動することで、コンテナが存在する間ずっと DNS 解決を横取りし続ける
# [How]  --conf-file で設定ファイルを指定し、--log-facility でログを追記する
dnsmasq --conf-file="$DNSMASQ_CONF" --log-facility="$LOG_FILE"
log "dnsmasq started (listening on 127.0.0.1:53)"

# [What] コンテナの DNS 参照先を dnsmasq (127.0.0.1) に向け替える
# [Why]  全プロセスが DNS を引く際に必ず dnsmasq を経由するようにするため。
#        これにより、どのプロセスが github.com を解決しても ipset に自動追加される
cp /etc/resolv.conf /etc/resolv.conf.orig 2>/dev/null || true  # [Why] 元の状態をバックアップ
# [How]  nameserver 1行だけ書いて上書きすることで search ドメイン等は消えるが、
#        開発コンテナ内では通常問題にならない
echo "nameserver 127.0.0.1" > /etc/resolv.conf
log "resolv.conf updated to use local dnsmasq"

# [What] 主要な GitHub ドメインを先行して DNS 解決し、ipset を事前に温める
# [When] iptables ロックダウン前 (setup-firewall.sh のステップ2まで) に実施
# [Why]  iptables DROP が有効になる前に、少なくとも主要 IP が ipset に入っている状態にする。
#        dnsmasq を経由させることで解決と同時に ipset 追加も発生する
WARMUP_DOMAINS=(
  github.com
  api.github.com
  codeload.github.com
  objects.githubusercontent.com
  github-releases.githubusercontent.com
  copilot-proxy.githubusercontent.com
  default.exp-tas.com
)
log "Warming up DNS cache..."
for domain in "${WARMUP_DOMAINS[@]}"; do
  # [What] 各ドメインを dnsmasq (127.0.0.1:53) に問い合わせる
  # [Why]  dnsmasq の --ipset 機能は問い合わせを受けて応答を返す瞬間に ipset へ追加する。
  #        この dig コマンドがそのトリガーになる
  # [How]  @127.0.0.1 で明示的にローカル dnsmasq へ向ける。
  #        >/dev/null で出力を捨て、|| true で解決失敗 (NXDOMAIN 等) を無視する
  dig +short +time=3 +tries=1 A "$domain" @127.0.0.1 >/dev/null 2>&1 || true
done
log "DNS warmup complete"
